import FenceOutlinedIcon from '@mui/icons-material/FenceOutlined';
import GroupOutlined from '@mui/icons-material/GroupOutlined';
import ContactsOutlined from '@mui/icons-material/ContactsOutlined';
import CategoryOutlined from '@mui/icons-material/CategoryOutlined';
import CloudUploadOutlined from '@mui/icons-material/CloudUploadOutlined';
import CloudDownloadOutlined from '@mui/icons-material/CloudDownloadOutlined';
import LocalShippingOutlined from '@mui/icons-material/LocalShippingOutlined';
import AssessmentOutlined from '@mui/icons-material/AssessmentOutlined';
import SettingsOutlined from '@mui/icons-material/SettingsOutlined';
import DoDisturbOnOutlined from '@mui/icons-material/DoDisturbOnOutlined';
import HorizontalSplitOutlined from '@mui/icons-material/HorizontalSplitOutlined';
import FiberManualRecord from '@mui/icons-material/FiberManualRecord';
import KeyboardArrowDownOutlined from '@mui/icons-material/KeyboardArrowDownOutlined';


export const SidebarItems = [
    {
        id: 1,
        icon: <FenceOutlinedIcon fontSize="small" />,
        label: 'Home',
        dbname: 'home',
        route: '/home',
    },
    {
        id: 2,
        icon: <GroupOutlined fontSize="small" />,
        label: 'User Management',
        dbname: 'usermanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'user',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'User',
                dbname: 'alluser',
                route: '/usermanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'Role',
                dbname: 'allrole',
                route: '/usermanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Sales Commission Agents',
                dbname: 'allsalescommissionagent',
                route: '/usermanagement',
            }
        ]
    }, {
        id: 3,
        icon: <ContactsOutlined fontSize="small" />,
        label: 'Suppliers',
        dbname: 'suppliermanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'contact',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Add Suppliers',
                dbname: 'asupplier',
                route: '/suppliermanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'List Suppliers',
                dbname: 'allsupplier',
                route: '/suppliermanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Import Suppliers',
                dbname: 'isupplier',
                route: '/suppliermanagement',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'Import Supplier List',
                dbname: 'importsupplier',
                route: '/suppliermanagement',
            },
            {
                id: 8,
                icon: <FiberManualRecord />,
                label: 'Supplier Dues Report',
                dbname: 'supplierduereport',
                route: '/suppliermanagement',
            },
            {
                id: 9,
                icon: <FiberManualRecord />,
                label: 'Balance Wise Supplier Dues Report',
                dbname: 'balancewisesupduereport',
                route: '/suppliermanagement',
            },
            {
                id: 10,
                icon: <FiberManualRecord />,
                label: 'Supplier Overdues Report',
                dbname: 'supplieroverduereport',
                route: '/suppliermanagement',
            },
            {
                id: 11,
                icon: <FiberManualRecord />,
                label: 'Supplier Balance Abstract',
                dbname: 'supplierbalanceabstract',
                route: '/suppliermanagement',
            },
            {
                id: 12,
                icon: <FiberManualRecord />,
                label: 'Supplier Payments Report',
                dbname: 'supplierpaymentsreport',
                route: '/suppliermanagement',
            },
            {
                id: 13,
                icon: <FiberManualRecord />,
                label: 'Supplier Wise Payments Report',
                dbname: 'supplierwisepaymentsreport',
                route: '/suppliermanagement',
            },
            {
                id: 14,
                icon: <FiberManualRecord />,
                label: 'Supplier Bills Report',
                dbname: 'supplierbillsreport',
                route: '/suppliermanagement',
            },
            {
                id: 15,
                icon: <FiberManualRecord />,
                label: 'Supplier Report',
                dbname: 'suppliersreport',
                route: '/suppliermanagement',
            }
        ]
    },
    {
        id: 4,
        icon: <ContactsOutlined fontSize="small" />,
        label: 'Customers',
        dbname: 'customermanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'contact',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'ADD - Retail Customer',
                dbname: 'customermasterretail',
                route: '/customermanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'ADD - Wholesale Customer ',
                dbname: 'customermasterwholesale',
                route: '/customermanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Import Customers',
                dbname: 'icustomer',
                route: '/customermanagement',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'List Customers',
                dbname: 'allcustomer',
                route: '/customermanagement',
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: 'List Customer - Retail',
                dbname: 'importcustomerlistretail',
                route: '/customermanagement',
            },
            {
                id: 6,
                icon: <FiberManualRecord />,
                label: 'List Customer - Wholesale',
                dbname: 'importcustomerlistwsale',
                route: '/customermanagement',
            },
            {
                id: 7,
                icon: <FiberManualRecord />,
                label: 'List Customer Group',
                dbname: 'allcustomergrp',
                route: '/customermanagement',
            },
            {
                id: 8,
                icon: <FiberManualRecord />,
                label: 'Customer Payment Register',
                dbname: 'customerpaymentregister',
                route: '/customermanagement',
            },
            {
                id: 9,
                icon: <FiberManualRecord />,
                label: 'Customer Bills Register',
                dbname: 'customerbillsregister',
                route: '/customermanagement',
            },
            {
                id: 10,
                icon: <FiberManualRecord />,
                label: 'Customer Drug Entry',
                dbname: 'customerdrugentry',
                route: '/customermanagement',
            },
            {
                id: 11,
                icon: <FiberManualRecord />,
                label: 'Retail Follow Customer',
                dbname: 'retailfollowcustomer',
                route: '/customermanagement',
            },
            {
                id: 12,
                icon: <FiberManualRecord />,
                label: 'Wholesale Followup Customer',
                dbname: 'wholesalefollowcustomer',
                route: '/customermanagement',
            },
            {
                id: 13,
                label: '------------------------------------',
                dbname: 'customerpaymentregister',
                route: '/',
            },
            {
                id: 14,
                icon: <FiberManualRecord />,
                label: 'Customer Balance Register',
                dbname: 'customerbalanceregister',
                route: '/customermanagement',
            },
            {
                id: 15,
                icon: <FiberManualRecord />,
                label: 'Customer Dues Report',
                dbname: 'customerduesreport',
                route: '/customermanagement',
            },
            {
                id: 16,
                icon: <FiberManualRecord />,
                label: 'Customer Over Dues Report',
                dbname: 'Customeroverduesreport',
                route: '/customermanagement',
            },
            {
                id: 17,
                icon: <FiberManualRecord />,
                label: 'Customer Over Dues Abstract',
                dbname: 'Customeroverdueabstract',
                route: '/customermanagement',
            },
            {
                id: 18,
                icon: <FiberManualRecord />,
                label: 'Balance Wise Customer Dues Report',
                dbname: 'Balanacewisecustomerduesreport',
                route: '/customermanagement',
            },
            {
                id: 19,
                icon: <FiberManualRecord />,
                label: 'Customer Account Statement',
                dbname: 'customeraccountstatement',
                route: '/customermanagement',
            },
            {
                id: 20,
                icon: <FiberManualRecord />,
                label: 'Customer Account Summary',
                dbname: 'customeraccountsummary',
                route: '/customermanagement',
            },
            {
                id: 21,
                icon: <FiberManualRecord />,
                label: 'Reference Wise Dues Report (Sales)',
                dbname: 'Referencewiseduesales',
                route: '/customermanagement',
            },
            {
                id: 22,
                icon: <FiberManualRecord />,
                label: 'Reference Wise Dues Report (Estimates)',
                dbname: 'Referencewiseduesreport',
                route: '/customermanagement',
            },
            {
                id: 23,
                icon: <FiberManualRecord />,
                label: 'Customer Payment Report',
                dbname: 'customerpaymentreport',
                route: '/customermanagement',
            },
            {
                id: 24,
                icon: <FiberManualRecord />,
                label: 'Customer Wise Payment Report',
                dbname: 'customerwisepaymentreport',
                route: '/customermanagement',
            },
            {
                id: 25,
                icon: <FiberManualRecord />,
                label: 'Reference Wise Payments Report',
                dbname: 'Referencewisepaymentreport',
                route: '/customermanagement',
            },
            {
                id: 26,
                icon: <FiberManualRecord />,
                label: 'Reference Wise Payments Summary',
                dbname: 'Referencewisepaymentsummary',
                route: '/customermanagement',
            },
            {
                id: 27,
                icon: <FiberManualRecord />,
                label: 'Remarks Wise Report',
                dbname: 'Remarkswisereport',
                route: '/customermanagement',
            },
            {
                id: 28,
                icon: <FiberManualRecord />,
                label: 'Customer Bills Report',
                dbname: 'customerbillsreport',
                route: '/customermanagement',
            },
            {
                id: 29,
                icon: <FiberManualRecord />,
                label: 'Customers List',
                dbname: 'customerslist',
                route: '/customermanagement',
            },
            {
                id: 30,
                icon: <FiberManualRecord />,
                label: 'Area Wise Customer List',
                dbname: 'creawisecustomerlist',
                route: '/customermanagement',
            },
        ]
    },
    {
        id: 5,
        icon: <CategoryOutlined fontSize="small" />,
        label: 'Products',
        dbname: 'productmanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'product',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Category',
                dbname: 'allcategory',
                route: '/productmanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'Schedule',
                dbname: 'allschedule',
                route: '/productmanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Add Products',
                dbname: 'aproduct',
                route: '/productmanagement',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'Import Products',
                dbname: 'iproduct',
                route: '/productmanagement',
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: 'List products',
                dbname: 'allproduct',
                route: '/productmanagement',
            },
            {
                id: 6,
                icon: <FiberManualRecord />,
                label: 'Discount',
                dbname: 'alldiscount',
                route: '/productmanagement',
            },
            {
                id: 7,
                icon: <FiberManualRecord />,
                label: 'Category Item List',
                dbname: 'categoryitemlist',
                route: '/productmanagement',
            },
            {
                id: 8,
                icon: <FiberManualRecord />,
                label: 'Molecule Item list',
                dbname: 'moleculelist',
                route: '/productmanagement',
            },
            {
                id: 9,
                icon: <FiberManualRecord />,
                label: 'Manufacture Item list',
                dbname: 'manufacturelist',
                route: '/productmanagement',
            },
            {
                id: 10,
                icon: <FiberManualRecord />,
                label: 'Schedule Item list',
                dbname: 'schedulelist',
                route: '/productmanagement',
            },
            {
                id: 11,
                icon: <FiberManualRecord />,
                label: 'Category Item Summary',
                dbname: 'categoryitemsummary',
                route: '/productmanagement',
            },
            {
                id: 12,
                icon: <FiberManualRecord />,
                label: 'Molecule Item Summary',
                dbname: 'moleculesummary',
                route: '/productmanagement',
            },
            {
                id: 13,
                icon: <FiberManualRecord />,
                label: 'Manufacture Item Summary',
                dbname: 'manufacturesummary',
                route: '/productmanagement',
            },
        ]
    },
    {
        id: 6,
        icon: <CloudUploadOutlined fontSize="small" />,
        label: 'Purchases',
        dbname: 'purchasemanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'purchase',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Add Purchase',
                dbname: 'apurchase',
                route: '/purchasemanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'List Purchase',
                dbname: 'allpurchase',
                route: '/purchasemanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Purchase Order',
                dbname: 'allpurchaseorder',
                route: '/purchasemanagement',
            },
        ]
    },
    {
        id: 7,
        icon: <CloudDownloadOutlined fontSize="small" />,
        label: 'Sell',
        dbname: 'sellmanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'sell',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'POS',
                dbname: 'apos',
                route: '/sellmanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'List POS',
                dbname: 'allpos',
                route: '/sellmanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Add Draft',
                dbname: 'adraft',
                route: '/sellmanagement',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'List Drafts',
                dbname: 'alldraft',
                route: '/sellmanagement',
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: 'Add Quotation',
                dbname: 'aquotation',
                route: '/sellmanagement',
            },
            {
                id: 6,
                icon: <FiberManualRecord />,
                label: 'List Quatations',
                dbname: 'allquotation',
                route: '/sellmanagement',
            },
        ]
    },
    {
        id: 8,
        icon: <DoDisturbOnOutlined fontSize="small" />,
        label: 'Expenses',
        arrow: <KeyboardArrowDownOutlined />,
        dbname: 'expensemanagement',
        name: 'expenses',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Add Expenses',
                dbname: 'aexpense',
                route: '/expensemanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'List Expenses',
                dbname: 'allexpense',
                route: '/expensemanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Expenses Categories',
                dbname: 'allexpensecategory',
                route: '/expensemanagement',
            }
        ]
    },
    {
        id: 11,
        icon: <AssessmentOutlined fontSize="small" />,
        label: 'Reports',
        arrow: <KeyboardArrowDownOutlined />,
        dbname: 'reportmanagement',
        name: 'report',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Bill Wise Profit Wholesale',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'Bill Wise Profit Retail',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Bill Wise Profit Estimate',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'Day Wise Profit Wholesale',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: 'Day Wise Profit Retail',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 6,
                icon: <FiberManualRecord />,
                label: 'Day Wise Profit Estimate',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 7,
                icon: <FiberManualRecord />,
                label: 'Item Wise Profit Wholesale',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 8,
                icon: <FiberManualRecord />,
                label: 'Item Wise Profit Retail',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 9,
                icon: <FiberManualRecord />,
                label: 'Item Wise Profit Estimate',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 10,
                icon: <FiberManualRecord />,
                label: 'Customer Wise Profit Wholesale',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 11,
                icon: <FiberManualRecord />,
                label: 'Customer Wise Profit Estimate',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 12,
                icon: <FiberManualRecord />,
                label: 'Reference Summary',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 13,
                icon: <FiberManualRecord />,
                label: 'Reference Comparison',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },
            {
                id: 14,
                icon: <FiberManualRecord />,
                label: 'Customer Comparison',
                dbname: 'aexpense',
                route: '/reportmanagement',
            },   
        ]
    },
    {
        id: 9,
        icon: <SettingsOutlined fontSize="small" />,
        label: 'Account',
        dbname: 'CheckBank',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'Account',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Cash Book Register',
                dbname: 'businesssettings',
                route: '/CheckBank',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'Batch Wise Stock Report',
                dbname: 'Batchwisestackrep',
                route: '/CheckBank',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Batch Wise Stock Detail',
                dbname: 'Batchwisestockdet',
                route: '/CheckBank',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'Profit & Loss Account',
                dbname: 'businesssettings',
                route: '/CheckBank',
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: 'Trail Balance',
                dbname: 'businesssettings',
                route: '/CheckBank',
            },
            {
                id: 6,
                icon: <FiberManualRecord />,
                label: 'Group Summary',
                dbname: 'businesssettings',
                route: '/CheckBank',
            },
            {
                id: 7,
                icon: <FiberManualRecord />,
                label: 'Bank Statement',
                dbname: 'businesssettings',
                route: '/CheckBank',
            },
            {
                id: 8,
                icon: <FiberManualRecord />,
                label: 'Cash Book Report',
                dbname: 'CashBookReport',
                route: '/CheckBank',
            },
            {
                id: 9,
                label: 'Cash Book Register Report',
                dbname: 'CashbookRegreport',
                route: '/CheckBank',
            },
            {
                id: 10,
                icon: <FiberManualRecord />,
                label: "Day Book Printing",
                dbname: "allexpense",
                route: "/CheckBank",
            },
            {
                id: 11,
                icon: <FiberManualRecord />,
                label: "Account And Group Creation",
                dbname: "allexpense",
                route: "/CheckBank",
            },

        ]
    }, {
        id: 10,
        icon: <DoDisturbOnOutlined fontSize="small" />,
        label: "Bank",
        arrow: <KeyboardArrowDownOutlined />,
        dbname: "bankmanagement",
        name: "bank",
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: "Bank Master",
                dbname: "bankmaster",
                route: "/bankmanagement",
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: "List Bank Master",
                dbname: "listbankmaster",
                route: "/bankmanagement",
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: "Bank Book Register",
                dbname: "bankbookregister",
                route: "/bankmanagement",
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: "Bank List",
                dbname: "banklist",
                route: "/bankmanagement",
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: "Bank Book Report",
                dbname: "bankbookreport",
                route: "/bankmanagement",
            },
        ],
    },
    {
        id: 11,
        icon: <SettingsOutlined fontSize="small" />,
        label: 'Settings',
        dbname: 'settingsmanagement',
        arrow: <KeyboardArrowDownOutlined />,
        name: 'setting',
        children: [
            {
                id: 1,
                icon: <FiberManualRecord />,
                label: 'Business Settings',
                dbname: 'businesssettings',
                route: '/settingsmanagement',
            },
            {
                id: 2,
                icon: <FiberManualRecord />,
                label: 'Business Location',
                dbname: 'allbusinesslocation',
                route: '/settingsmanagement',
            },
            {
                id: 3,
                icon: <FiberManualRecord />,
                label: 'Alpharate',
                dbname: 'allalpharate',
                route: '/settingsmanagement',
            },
            {
                id: 4,
                icon: <FiberManualRecord />,
                label: 'Tax Rates',
                dbname: 'alltaxrate',
                route: '/settingsmanagement',
            },
            {
                id: 5,
                icon: <FiberManualRecord />,
                label: 'HSN Wise Report Retails',
                dbname: 'alltaxrate',
                route: '/settingsmanagement',
            },
            {
                id: 6,
                icon: <FiberManualRecord />,
                label: 'HSN Wise Report Whole Sale',
                dbname: 'alltaxrate',
                route: '/settingsmanagement',
            },
            {
                id: 7,
                icon: <FiberManualRecord />,
                label: 'HSN Wise Report Whole Sale Return',
                dbname: 'alltaxrate',
                route: '/settingsmanagement',
            },
            {
                id: 8,
                icon: <FiberManualRecord />,
                label: 'HSN Wise Report Retail Sales Return',
                dbname: 'alltaxrate',
                route: '/settingsmanagement',
            },
            {
                id: 9,
                icon: <FiberManualRecord />,
                label: 'Payment Integration',
                dbname: 'allpaymentintegration',
                route: '/settingsmanagement',
            },
            {
                id: 10,
                icon: <FiberManualRecord />,
                label: 'Table View',
                dbname: 'allpaymentintegration',
                route: '/settingsmanagement',
            }
        ]
    },
]
